let $v = 0;
export const SERVER_HEADER = {
  ADD_CLIENT: $v++,
  SET_OUR_ENTITY: $v++,
  UPDATE_ENTITY: $v++,
  CONFIG: $v++,
  REMOVE_ENTITY: $v++,
  ADD_ENTITY: $v++,
  SWAP_ITEM: $v++,
  ACTION: $v++,
  HIT_BOUNCE_EFFECT: $v++,
  DIED: $v++,
  INVENTORY: $v++,
  UPDATE_HEALTH: $v++,
  LEADERBOARD: $v++,
  HEALTH: $v++,
  CHAT: $v++,
  PING: $v++,
  PING_RESPONSE: $v++,
  BUILD_MODE: $v++,
  HURT: $v++,
  HUNGER: $v++,
  TEMPERATURE: $v++,
}

export const CLIENT_HEADER = {
  REQUEST_RESPAWN: 0,
  INPUT: 1,
  MOUSE_DOWN: 2,
  MOUSE_UP: 3,
  INVENTORY: 4,
  CHAT: 5,
  PONG: 6,
  EQUIP: 7,
  CRAFT: 8,
}